### ISSUE TITLE
Downloading stops Release mode only!

### ISSUE THREAD

**Issue by khaledkhj** [MindorksOpenSource/PRDownloader#26]
It works really great in debugging (Development) mode only!
The downloading process stops for the release version of the app!

I am getting these exceptions
```
java.io.IOException: write failed: EBADF (Bad file descriptor)
java.io.SyncFailedException: sync failed
```

Any help?

Thank you.

**Comment by amitshekharhike** [comment]
Have you applied proguard?

**Comment by amitshekhariitbhu** [comment]
Have you applied proguard?

**Comment by khaledkhj** [comment]
Yes I have

**Comment by khaledkhj** [comment]
How does Proguard effect that?

**Comment by skadyrov** [comment]
I am getting the same error, even in debug build. It starts download properly, but happens while downloading is in progress.

See the stack trace below:
`W/System.err: java.io.IOException: write failed: EBADF (Bad file descriptor)
     at libcore.io.IoBridge.write(IoBridge.java:501)
     at java.io.FileOutputStream.write(FileOutputStream.java:316)
     at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
     at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
     at com.downloader.internal.DownloadTask.closeAllSafely(DownloadTask.java:362)
     at com.downloader.internal.DownloadTask.run(DownloadTask.java:235)
     at com.downloader.internal.DownloadRunnable.run(DownloadRunnable.java:45)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at com.downloader.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:45)
     at java.lang.Thread.run(Thread.java:761)
 Caused by: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
     at libcore.io.Posix.writeBytes(Native Method)
     at libcore.io.Posix.write(Posix.java:273)
     at libcore.io.BlockGuardOs.write(BlockGuardOs.java:319)
     at libcore.io.IoBridge.write(IoBridge.java:496)
 	... 12 more
 java.io.SyncFailedException: sync failed
     at java.io.FileDescriptor.sync(Native Method)
     at com.downloader.internal.DownloadTask.closeAllSafely(DownloadTask.java:369)
     at com.downloader.internal.DownloadTask.run(DownloadTask.java:235)
     at com.downloader.internal.DownloadRunnable.run(DownloadRunnable.java:45)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at com.downloader.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:45)
     at java.lang.Thread.run(Thread.java:761)`

**Comment by skadyrov** [comment]
I am getting this error again. I am receiving it at 
```
    void onError(Error error);
```
of `OnDownloadListener`. 
In addition to that, error has `isServerError == false` and `isConnectionError == true`.

**Comment by skadyrov** [comment]
Would like to investigate this if you could give me an idea on where to start, or what could be the cause

**Comment by amitshekhariitbhu** [comment]
Ideally it should not happen. But it may occur because of so many file downloads.

**Comment by skadyrov** [comment]
I download only one zip file, about 170MB. It usually works, but occasionally it throws this error.

**Comment by ShurikuS57** [comment]
Confirm. I have the same mistake.

**Comment by articgram** [comment]
Confirm. I have the same mistake.

**Comment by hshahdoost** [comment]
Any updates on this error?

**Comment by hshahdoost** [comment]
I have spent 2 days replacing android downloadmanager with PRDownloader in my project, now after making the release I have faced this error, If this library doesn't work with pro guard (or has unknown errors in some cases) please explain it on the documentations!! and stop wasting people's time!

**Comment by amitshekhariitbhu** [comment]
@hshahdoost  Please give us sometime, we will check again and update today.

**Comment by amitshekhariitbhu** [comment]
@hshahdoost Meanwhile, can u please provide the logs for the error if possible.

**Comment by hshahdoost** [comment]
I'm getting the same error as everyone else,

```
04-16 15:28:18.566 4965-5029 W/System.err: java.io.IOException: write failed: EBADF (Bad file descriptor)
04-16 15:28:18.566 4965-5029 W/System.err:     at libcore.io.IoBridge.write(IoBridge.java:501)
04-16 15:28:18.566 4965-5029 W/System.err:     at java.io.FileOutputStream.write(FileOutputStream.java:316)
04-16 15:28:18.566 4965-5029 W/System.err:     at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
04-16 15:28:18.566 4965-5029 W/System.err:     at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
04-16 15:28:18.566 4965-5029 W/System.err:     at com.downloader.internal.DownloadTask.closeAllSafely(DownloadTask.java:362)
04-16 15:28:18.566 4965-5029 W/System.err:     at com.downloader.internal.DownloadTask.run(DownloadTask.java:235)
04-16 15:28:18.566 4965-5029 W/System.err:     at com.downloader.internal.DownloadRunnable.run(DownloadRunnable.java:45)
04-16 15:28:18.566 4965-5029 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
04-16 15:28:18.566 4965-5029 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-16 15:28:18.566 4965-5029 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-16 15:28:18.566 4965-5029 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-16 15:28:18.566 4965-5029 W/System.err:     at com.downloader.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:45)
04-16 15:28:18.566 4965-5029 W/System.err:     at java.lang.Thread.run(Thread.java:761)
04-16 15:28:18.566 4965-5029 W/System.err: Caused by: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
04-16 15:28:18.566 4965-5029 W/System.err:     at libcore.io.Posix.writeBytes(Native Method)
04-16 15:28:18.566 4965-5029 W/System.err:     at libcore.io.Posix.write(Posix.java:273)
04-16 15:28:18.566 4965-5029 W/System.err:     at libcore.io.BlockGuardOs.write(BlockGuardOs.java:319)
04-16 15:28:18.566 4965-5029 W/System.err:     at libcore.io.IoBridge.write(IoBridge.java:496)
04-16 15:28:18.566 4965-5029 W/System.err: 	... 12 more
04-16 15:28:18.567 4965-5029 W/System.err: java.io.SyncFailedException: sync failed
04-16 15:28:18.567 4965-5029 W/System.err:     at java.io.FileDescriptor.sync(Native Method)
04-16 15:28:18.567 4965-5029 W/System.err:     at com.downloader.internal.DownloadTask.closeAllSafely(DownloadTask.java:369)
04-16 15:28:18.567 4965-5029 W/System.err:     at com.downloader.internal.DownloadTask.run(DownloadTask.java:235)
04-16 15:28:18.567 4965-5029 W/System.err:     at com.downloader.internal.DownloadRunnable.run(DownloadRunnable.java:45)
04-16 15:28:18.567 4965-5029 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
04-16 15:28:18.567 4965-5029 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-16 15:28:18.567 4965-5029 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-16 15:28:18.567 4965-5029 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-16 15:28:18.567 4965-5029 W/System.err:     at com.downloader.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:45)
04-16 15:28:18.567 4965-5029 W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

I have disabled proguard, or even minify configs but still get the same error.

**Comment by hshahdoost** [comment]
I have attached the source to my project to find the actual cause, Up until now I have found out that the actual cause of this exception is the following line
```
DownloadTask.java:204 sendProgress();
```
this line is calling the progress callback, the problem is how we handle the callback, because with an empty `onProgressListener` I got no errors. I'm trying to investigate more. I am using RxJava and calling the PRDownloader inside a `Flowable` (which uses `BackpressureStrategy.DROP`)

**Comment by amitshekhariitbhu** [comment]
@hshahdoost 
1. So is it happening without proguard also?
2. Only in release build?

**Comment by hshahdoost** [comment]
I couldn't figure why `RandomAccessFile` keeps invalidating the `FileDescriptor` but somehow after my code in the ui thread was being executed the `FileDescriptor` became invalid (`filedescriptor.valid() = false`). It was all solved after I removed RandomAccessFile from the source. Now it is working right. it looks somehow like this now.
before `DownloadTask.java : run() : 174`
```    
            RandomAccessFile randomAccess = new RandomAccessFile(file, "rw");
            fileDescriptor = randomAccess.getFD();
            outputStream = new BufferedOutputStream(new FileOutputStream(fileDescriptor));
```
after
```
            FileOutputStream fos = new FileOutputStream(file);
            outputStream = new BufferedOutputStream(fos);
            fileDescriptor = fos.getFD(); 
```

**Comment by hshahdoost** [comment]
@amitshekhariitbhu 
1.  yes with or without proguard, the error happens
2.  yes, I don't know why but it only works in the release mode

**Comment by droidluv** [comment]
This happens for me too, what happens is for me when in release the OnError gets called every now and then and if I restart it with a delay of few seconds it resumes downloading, really frustrating issue, gonna look at other solutions

**Comment by hshahdoost** [comment]
@droidluv try "Fetch" I have personally moved to that library, And now it's working perfectly.

**Comment by amitshekhariitbhu** [comment]
@hshahdoost Can you help here?
Just comment these two lines in the `DownloadTask` and try
```
outputStream.flush();
fileDescriptor.sync();
```

**Comment by droidluv** [comment]
@hshahdoost thanks for the suggestion will keep Fetch in mind, meanwhile I moved onto RxDownload, which is really good and with the power of Rx its quite frankly amazing, it has chunk based downloading and its quite fast and has amazing resume support, PRDownloader was taking around 1-2 minutes to download a 80MB file from Amazon S3 bucket, and RxDownload did the same file in 8 seconds (I have 250Mbps connection btw)

**Comment by amitshekhariitbhu** [comment]
@hshahdoost @droidluv @ShurikuS57 @articgram @khaledkhj @skadyrov 
Sorry for the delay. I have fixed the release mode issue. Please try the updated library and confirm me.

`compile 'com.mindorks.android:prdownloader:0.3.0'`

**Comment by pietro309** [comment]
Same error in release mode with proguard

implementation 'com.mindorks.android:prdownloader:0.4.0'

**Comment by WilsonChristian94** [comment]
Any solution for this issue? it's still happening in Release mode. It always gives Connection Error in release mode.

**Comment by AD7GAMER** [comment]
Download getting failed in release mode with proguard

**Comment by AD7GAMER** [comment]
@amitshekhariitbhu I'm still facing this issue with 'com.mindorks.android:prdownloader:0.4.0'. Kindly help me out.

**Comment by oguzhanozdemir** [comment]
@amitshekhariitbhu I'm still.. in 0.4.0.. help us..

**Comment by rlawlsah1028** [comment]
@amitshekhariitbhu add proguard option

-keep class com.downloader.** {*;}

**Comment by amitshekhariitbhu** [comment]
@rlawlsah1028 Is it working after the proguard in release mode for you?

**Comment by KushGoyal** [comment]
@amitshekhariitbhu I am facing this issue in debug mode too. In some devices it is working fine but in some it is not.

```
isConnectionError=true
isServerError=false
```

**Comment by KushGoyal** [comment]
@amitshekhariitbhu 

I migrated to fetch and found out that in newer android version http requests are not allowed. After changing the url to https the download started working.

Probably it was the same issue with PRdownloader lib. But i was not able to figure it out because of no info the error.

Making errors more verbose can help.
