### ISSUE TITLE
V/dfdf: com.downloader.Error@cb45940

### ISSUE THREAD

**Issue by mudi256** [MindorksOpenSource/PRDownloader#35]
what type of error?

**Comment by amitshekhariitbhu** [comment]
Sorry for the delay. I have fixed the release mode issue. Please try the updated library and confirm me.

`compile 'com.mindorks.android:prdownloader:0.3.0'`

**Comment by kikipryd** [comment]
@amitshekhariitbhu I have same issue, and I try to update to 'com.mindorks.android:prdownloader:0.3.0'. But still not work

**Comment by Amirhf1** [comment]
I'm error com.downloader.Error@243c561 
What solution do you have to solve this problem?

**Comment by arishrehmankhan** [comment]
> @amitshekhariitbhu I have same issue, and I try to update to 'com.mindorks.android:prdownloader:0.3.0'. But still not work

Check that you have storage permissions.
